package cli

import (
	"os"
	"path/filepath"
	"strings"
)

// detectCurrentShell returns the shell name ("bash" or "zsh") for the current invocation.
// Reads $AKA_SHELL first (set by the wrapper generated by `aka init`), then parses $SHELL.
func detectCurrentShell() string {
	if s := os.Getenv("AKA_SHELL"); s != "" {
		return s
	}
	return shellNameFromPath(os.Getenv("SHELL"))
}

// shellNameFromPath converts a $SHELL path like "/bin/zsh" to a short name.
func shellNameFromPath(shellPath string) string {
	switch {
	case strings.Contains(shellPath, "zsh"):
		return "zsh"
	case strings.Contains(shellPath, "bash"):
		return "bash"
	default:
		return ""
	}
}

// rcFileForShell returns the RC file path for the given shell.
func rcFileForShell(shell string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	switch shell {
	case "zsh":
		return filepath.Join(home, ".zshrc"), nil
	case "bash":
		rc := filepath.Join(home, ".bashrc")
		profile := filepath.Join(home, ".bash_profile")
		if _, err := os.Stat(profile); err == nil {
			if _, err2 := os.Stat(rc); os.IsNotExist(err2) {
				return profile, nil
			}
		}
		return rc, nil
	default:
		return filepath.Join(home, ".bashrc"), nil
	}
}

// isShellInitialized reports whether ~/.config/aka/<shell>/ exists.
func isShellInitialized(shell string) (bool, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return false, err
	}
	_, err = os.Stat(filepath.Join(home, ".config", "aka", shell))
	if os.IsNotExist(err) {
		return false, nil
	}
	return err == nil, err
}

// requireShellInitialized prints a friendly message and returns false if the shell
// has not been initialized. Callers should return nil when this returns false.
func requireShellInitialized(shell string) (bool, error) {
	if shell == "" {
		return false, nil
	}
	ok, err := isShellInitialized(shell)
	if err != nil {
		return false, err
	}
	if !ok {
		return false, nil
	}
	return true, nil
}
